using Microsoft.EntityFrameworkCore;
using MinimalAPIsMovies.Data;
using MinimalAPIsMovies.Models;

namespace MinimalAPIsMovies.Repositories
{
	public class GenreRepository : IGenreRepository
	{
		private readonly ApplicationDbContext _context;

		public GenreRepository(ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<int> Create(Genre genre)
		{
			await _context.AddAsync(genre);
			await _context.SaveChangesAsync();
			return genre.Id; // Assuming Id is auto-generated by the database
		}

		public async Task<IEnumerable<Genre>> GetAll()
		{
			return await _context.Genres.ToListAsync(); // Assuming you want to return all genres
		}

		public async Task<Genre?> GetById(int id)
		{
			return await _context.Genres.FindAsync(id); // Assuming you want to find a genre by its ID
		}
	}
}
