using MinimalAPIsMovies.Data;
using MinimalAPIsMovies.Models;

namespace MinimalAPIsMovies.Repositories
{
	public class GenreRepository : IGenreRepository
	{
		private readonly ApplicationDbContext _context;

		public GenreRepository(ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<int> Create(Genre genre)
		{
			await _context.AddAsync(genre);
			await _context.SaveChangesAsync();
			return genre.Id; // Assuming Id is auto-generated by the database
		}
	}
}
